package com.reiner.greenflix.view;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import com.google.android.material.button.MaterialButton;
import com.google.android.material.textfield.TextInputEditText;
import com.reiner.greenflix.R;
import com.reiner.greenflix.controller.FilmController;
import com.reiner.greenflix.model.Film;

public class AddFragment extends Fragment {

    private TextInputEditText etTitle, etGenre, etPosterUrl, etCoverUrl, etRating, etTrailerUrl, etDescription;
    private MaterialButton btnSave;
    private FilmController controller;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_add, container, false);

        controller = new FilmController(getContext());

        etTitle = view.findViewById(R.id.etTitle);
        etGenre = view.findViewById(R.id.etGenre);
        etPosterUrl = view.findViewById(R.id.etPosterUrl);
        etCoverUrl = view.findViewById(R.id.etCoverUrl);
        etRating = view.findViewById(R.id.etRating);
        etTrailerUrl = view.findViewById(R.id.etTrailerUrl);
        etDescription = view.findViewById(R.id.etDescription);
        btnSave = view.findViewById(R.id.btnAddMovie);

        btnSave.setOnClickListener(v -> saveMovie());

        return view;
    }

    private void saveMovie() {
        String title = etTitle.getText().toString().trim();
        String genre = etGenre.getText().toString().trim();
        String poster = etPosterUrl.getText().toString().trim();
        String cover = etCoverUrl.getText().toString().trim();
        String rating = etRating.getText().toString().trim();
        String trailer = etTrailerUrl.getText().toString().trim();
        String desc = etDescription.getText().toString().trim();

        if (title.isEmpty() || genre.isEmpty() || poster.isEmpty() || desc.isEmpty()) {
            Toast.makeText(getContext(), "Please fill title, genre, poster and description", Toast.LENGTH_SHORT).show();
            return;
        }

        // ID will be generated by MockAPI
        Film newFilm = new Film("", title, genre, poster, cover, desc, rating, trailer);

        btnSave.setEnabled(false);
        btnSave.setText("Saving...");

        controller.addFilm(newFilm, new FilmController.SingleDataCallback() {
            @Override
            public void onSuccess(Film film) {
                if (!isAdded()) return;
                Toast.makeText(getContext(), "Movie added successfully!", Toast.LENGTH_SHORT).show();
                clearFields();
                btnSave.setEnabled(true);
                btnSave.setText("SAVE MOVIE");
            }

            @Override
            public void onError(String errorMessage) {
                if (!isAdded()) return;
                Toast.makeText(getContext(), errorMessage, Toast.LENGTH_SHORT).show();
                btnSave.setEnabled(true);
                btnSave.setText("SAVE MOVIE");
            }
        });
    }

    private void clearFields() {
        etTitle.setText("");
        etGenre.setText("");
        etPosterUrl.setText("");
        etCoverUrl.setText("");
        etRating.setText("");
        etTrailerUrl.setText("");
        etDescription.setText("");
    }
}